import { FileText, Image, Layers, Sparkles, Table } from 'lucide-react';
import { motion } from 'framer-motion';

const fileTypes = [{ label: 'PDF', Icon: FileText, color: '#EA4335' }, { label: 'Spreadsheet', Icon: Table, color: '#34A853' }, { label: 'Image', Icon: Image, color: '#4A90D9' }, { label: 'Text', Icon: FileText, color: '#9B72CF' }];

export default function EmptyCanvasState() {
  const open = () => window.dispatchEvent(new Event('aether:open-dialog'));
  return <div className="pointer-events-none absolute inset-0 z-10 grid place-items-center"><div className="pointer-events-auto flex max-w-[390px] flex-col items-center text-center"><motion.span animate={{ y: [-6, 6, -6] }} className="mb-5 grid h-14 w-14 place-items-center rounded-[18px] border border-white/90 bg-white/80 text-[#4A90D9] shadow-[0_8px_24px_rgba(74,144,217,0.14)]" transition={{ duration: 3, ease: 'easeInOut', repeat: Infinity }}><Sparkles size={26} /></motion.span><h1 className="text-[24px] font-bold tracking-[-0.04em] text-[#1A1A1A]">Drop files to begin</h1><p className="mt-3 text-[14px] leading-6 text-[#919197]">Drag files from your computer onto this canvas. Aether will understand them and connect the dots.</p><div className="mt-6 grid grid-cols-2 gap-2.5">{fileTypes.map(({ label, Icon, color }) => <button className="flex items-center gap-2 rounded-[8px] border border-[#E8E8EC] bg-white px-4 py-2.5 text-[12px] font-medium text-[#55555A] shadow-[0_1px_3px_rgba(0,0,0,0.03)] transition hover:-translate-y-0.5 hover:scale-[1.02] hover:shadow-[0_5px_12px_rgba(0,0,0,0.08)]" key={label} onClick={open} type="button"><Icon color={color} size={16} />{label}</button>)}</div><span className="my-4 text-[12px] text-[#C4C4C9]">or</span><button className="flex items-center gap-2 rounded-[8px] border border-[#DDDBD8] px-5 py-2.5 text-[13px] font-medium text-[#55555A] transition hover:bg-[#F5F4F2]" onClick={open} type="button"><Layers size={16} />Browse files</button></div></div>;
}
