import { AnimatePresence, motion } from 'framer-motion';
import { Handle, Position, useUpdateNodeInternals, type Node, type NodeProps } from '@xyflow/react';
import { BookOpen, CarFront, Check, CheckSquare, ChevronDown, Clipboard, Download, FileText, ListChecks, Map, MapPin, MoreHorizontal, Plane, Plus, Sparkles as SparklesIcon, Wallet, X } from 'lucide-react';
import { useEffect, useMemo, useState, type ComponentType } from 'react';

import type { AnalyzedFile, DashboardBudgetRow, DashboardModule, DashboardModuleKind, DashboardPackingItem, DashboardPlan, DashboardState, RelationshipType, SuggestedCluster } from '../../../../shared/types';
import InteractiveMap, { type DashboardLocation } from './InteractiveMap';

export type SummaryCardNodeData = { cluster: SuggestedCluster; files: AnalyzedFile[]; dashboard?: DashboardState; dashboardPlan?: DashboardPlan; assemblyDelay?: number };
export type SummaryCardNodeType = Node<SummaryCardNodeData, 'summaryCard'>;

const COLORS: Record<RelationshipType, string> = { dates: '#4A90D9', cost: '#34A853', place: '#EA4335', tasks: '#9B72CF' };
const iconForKind: Record<DashboardModuleKind, ComponentType<{ size?: number; strokeWidth?: number }>> = { overview: SparklesIcon, timeline: Plane, budget: Wallet, checklist: CheckSquare, map: Map, tasks: ListChecks, topics: BookOpen, resources: FileText, results: SparklesIcon };
const iconForPlan = { sparkles: SparklesIcon, plane: Plane, wallet: Wallet, 'check-square': CheckSquare, map: Map, 'list-checks': ListChecks, 'book-open': BookOpen, 'file-text': FileText } as const;
const relationshipFor = (kind: DashboardModuleKind): RelationshipType | null => ({ timeline: 'dates', budget: 'cost', checklist: 'tasks', tasks: 'tasks', map: 'place' } as Partial<Record<DashboardModuleKind, RelationshipType>>)[kind] ?? null;
const colorFor = (module: DashboardModule) => module.accent === 'dates' ? COLORS.dates : module.accent === 'cost' ? COLORS.cost : module.accent === 'place' ? COLORS.place : module.accent === 'tasks' ? COLORS.tasks : '#9B72CF';
const value = (data: Record<string, unknown>, key: string) => typeof data[key] === 'string' ? data[key] : '';
const money = (amount: number, currency: string) => new Intl.NumberFormat('en-US', { style: 'currency', currency, maximumFractionDigits: 0 }).format(amount);
const emit = (name: string, detail: unknown) => window.dispatchEvent(new CustomEvent(name, { detail }));
const dataValue = (files: AnalyzedFile[], key: string) => files.map((file) => value(file.smartPreview.displayData, key)).find(Boolean) ?? '';
type ModuleWithoutCompact = Omit<DashboardModule, 'compact'>;

function compactFor(module: ModuleWithoutCompact, files: AnalyzedFile[]) {
  if (module.visual === 'route-rail') return { primary: dataValue(files, 'origin') || files.flatMap((file) => file.entities.dates)[0]?.display || 'Start', secondary: dataValue(files, 'destination') || files.flatMap((file) => file.entities.dates).at(-1)?.display || 'Next', tertiary: dataValue(files, 'checkIn') || 'Next step' };
  if (module.visual === 'ring-metric') return { primary: dataValue(files, 'total') || 'Budget', secondary: 'Tracked', tertiary: `${files.flatMap((file) => file.entities.costs).length} items` };
  if (module.visual === 'progress') { const tasks = files.flatMap((file) => file.entities.tasks); return { primary: `${tasks.filter((task) => task.completed).length} / ${tasks.length}`, secondary: 'complete', tertiary: '' }; }
  if (module.visual === 'pin-map') { const locations = files.flatMap((file) => file.entities.locations); return { primary: locations[0]?.name ?? '', secondary: locations[1]?.name ?? '', tertiary: locations[2]?.name ?? '' }; }
  return { primary: module.title, secondary: `${module.sourceFileIds.length} source files`, tertiary: '' };
}

function fallbackPlan(files: AnalyzedFile[], cluster: SuggestedCluster): DashboardPlan {
  const modules: ModuleWithoutCompact[] = [{ id: 'overview', kind: 'overview', title: cluster.category === 'education' ? 'Key concepts' : 'Overview', summary: files.map((file) => file.summary).slice(0, 2).join(' '), icon: 'sparkles', accent: 'neutral', visual: 'key-points', interactions: ['expand', 'focus-source'], sourceFileIds: files.map((file) => file.id) }];
  if (files.some((file) => file.entities.dates.length)) modules.push({ id: 'timeline', kind: 'timeline', title: cluster.category === 'travel' ? 'Journey' : 'Timeline', summary: 'Important dates synthesized from your source files.', icon: 'plane', accent: 'dates', visual: cluster.category === 'travel' ? 'route-rail' : 'milestone-list', interactions: ['expand', 'focus-source', 'copy'], sourceFileIds: files.filter((file) => file.entities.dates.length).map((file) => file.id) });
  if (files.some((file) => file.entities.costs.length)) modules.push({ id: 'budget', kind: 'budget', title: 'Budget', summary: 'Editable amounts grounded in the files you added.', icon: 'wallet', accent: 'cost', visual: 'ring-metric', interactions: ['expand', 'edit-values', 'export'], sourceFileIds: files.filter((file) => file.entities.costs.length).map((file) => file.id) });
  if (files.some((file) => file.entities.tasks.length)) modules.push({ id: 'tasks', kind: 'tasks', title: cluster.category === 'travel' ? 'Packing' : 'Tasks', summary: 'Track the actionable items Aether found.', icon: 'list-checks', accent: 'tasks', visual: 'progress', interactions: ['expand', 'toggle-item', 'add-item'], sourceFileIds: files.filter((file) => file.entities.tasks.length).map((file) => file.id) });
  if (files.some((file) => file.entities.locations.length)) modules.push({ id: 'map', kind: 'map', title: cluster.category === 'travel' ? 'Map' : 'Places', summary: 'Places mentioned across this workspace.', icon: 'map', accent: 'place', visual: 'pin-map', interactions: ['expand', 'focus-source', 'open-map'], sourceFileIds: files.filter((file) => file.entities.locations.length).map((file) => file.id) });
  return { title: cluster.name, subtitle: cluster.dateRange, category: cluster.category, headerIcon: cluster.category === 'travel' ? 'map' : cluster.category === 'education' ? 'book-open' : 'sparkles', headerAccent: cluster.category === 'travel' ? 'place' : 'neutral', modules: modules.map((module) => ({ ...module, compact: compactFor(module, files) })) };
}

function CompactPreview({ module, color }: { module: DashboardModule; color: string }) {
  const compact = module.compact;
  if (module.visual === 'route-rail') return <div className="mt-2.5"><div className="flex items-center justify-between rounded-[8px] border border-[#E6E5E3] bg-[#FBFBFA] px-2.5 py-2"><span><b className="block text-[13px] text-[#303034]">{compact.primary}</b><small className="block text-[8px] text-[#7D7D83]">Departure</small></span><div className="mx-2 flex flex-1 items-center gap-1 text-[#7D7D83]"><span className="h-px flex-1 border-t border-dashed border-[#BBB9B4]" /><Plane size={17} className="shrink-0 text-[#55555A]" /><span className="h-px flex-1 border-t border-dashed border-[#BBB9B4]" /></div><span className="text-right"><b className="block text-[13px] text-[#303034]">{compact.secondary}</b><small className="block text-[8px] text-[#7D7D83]">Arrival</small></span></div>{compact.tertiary && <p className="mt-1.5 flex items-center gap-1.5 text-[9px] text-[#68686E]"><CarFront size={12} style={{ color }} />{compact.tertiary}</p>}</div>;
  if (module.visual === 'ring-metric') return <div className="mt-2.5 flex items-center gap-3"><div className="grid h-14 w-14 place-items-center rounded-full border-[7px] border-[#34A853] border-r-[#E8E7E4]"><b className="text-[10px] text-[#333337]">{compact.primary}</b></div><div className="min-w-0 space-y-1 text-[9px]"><p className="flex items-center gap-1.5 text-[#55555A]"><i className="h-2 w-2 rounded-full" style={{ backgroundColor: color }} />{compact.secondary}</p><p className="flex items-center gap-1.5 text-[#77777D]"><i className="h-2 w-2 rounded-full bg-[#B8B6B1]" />{compact.tertiary}</p></div></div>;
  if (module.visual === 'progress') { const match = compact.primary.match(/(\d+)\s*\/\s*(\d+)/); const progress = match ? Math.min(100, Number(match[1]) / Number(match[2]) * 100) : 55; return <div className="mt-2.5"><p className="text-[11px] text-[#55555A]"><b className="text-[21px] leading-none text-[#303034]">{compact.primary}</b> {compact.secondary}</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#E7E5E9]"><div className="h-full rounded-full" style={{ backgroundColor: color, width: `${progress}%` }} /></div></div>; }
  if (module.visual === 'pin-map') return <div className="relative mt-2.5 h-[70px] overflow-hidden rounded-[8px] border border-[#E5E2D9] bg-[#F1EEE7]" style={{ backgroundImage: 'linear-gradient(28deg, transparent 42%, rgba(255,255,255,.82) 43%, rgba(255,255,255,.82) 46%, transparent 47%), linear-gradient(112deg, transparent 48%, rgba(255,255,255,.75) 49%, rgba(255,255,255,.75) 52%, transparent 53%)' }}><MapPin className="absolute left-[22%] top-[34%]" fill={color} size={20} style={{ color }} /><MapPin className="absolute left-[50%] top-[48%]" fill={color} size={18} style={{ color }} /><MapPin className="absolute right-[20%] top-[20%]" fill={color} size={20} style={{ color }} /><span className="absolute bottom-1 left-2 text-[8px] text-[#4C4C51]">{compact.primary}</span><span className="absolute bottom-1 left-[42%] text-[8px] text-[#4C4C51]">{compact.secondary}</span><span className="absolute right-2 top-1 text-[8px] text-[#4C4C51]">{compact.tertiary}</span></div>;
  return <div className="mt-2.5 rounded-[7px] bg-[#F8F7F5] px-2.5 py-2 text-[10px] text-[#64646A]"><b className="block text-[#38383D]">{compact.primary}</b><span>{[compact.secondary, compact.tertiary].filter(Boolean).join(' · ')}</span></div>;
}

function ModuleShell({ module, open, onToggle, onHover, children }: { module: DashboardModule; open: boolean; onToggle: () => void; onHover: (active: boolean) => void; children: React.ReactNode }) {
  const [isOpen, setIsOpen] = useState(false);
  const Icon = iconForPlan[module.icon] ?? iconForKind[module.kind];
  const relationship = relationshipFor(module.kind);
  const color = colorFor(module);
  useEffect(() => setIsOpen(open), [open]);
  return <motion.section layout className="relative overflow-visible rounded-[11px] border border-[#DFDFE2] bg-[#FEFEFF] px-3 py-2.5 transition-shadow hover:shadow-[0_3px_10px_rgba(0,0,0,0.05)]" onMouseEnter={() => onHover(true)} onMouseLeave={() => onHover(false)} transition={{ duration: 0.22 }}>
    {relationship && <><Handle className="!h-[8px] !w-[8px] !border-0 !bg-transparent !opacity-0" id={`summary-${relationship}`} position={Position.Left} style={{ top: '50%' }} type="target" /><span aria-hidden className="pointer-events-none absolute left-[-10px] top-1/2 grid h-[18px] w-[18px] -translate-y-1/2 place-items-center rounded-full border-2 border-white shadow-[0_2px_8px_rgba(0,0,0,0.08)]" style={{ backgroundColor: color }}><span className="h-1.5 w-1.5 rounded-full bg-white" /></span></>}
    <button aria-expanded={isOpen} className="nodrag flex w-full items-center gap-2 text-left" onClick={onToggle} type="button"><span className="grid h-5 w-5 place-items-center rounded-full text-white" style={{ backgroundColor: color }}><Icon size={13} strokeWidth={2.4} /></span><span className="flex-1 text-[12px] font-semibold text-[#333337]">{module.title}</span><ChevronDown className={`text-[#89898F] transition-transform ${isOpen ? 'rotate-180' : ''}`} size={15} /></button>
    <CompactPreview color={color} module={module} />
    <AnimatePresence>{isOpen && <motion.div animate={{ opacity: 1, scale: 1, x: 0 }} className="nodrag absolute left-[calc(100%+62px)] top-0 z-50 w-[342px]" exit={{ opacity: 0, scale: 0.98, x: -8 }} initial={{ opacity: 0, scale: 0.98, x: -12 }} transition={{ duration: 0.22, ease: [0.22, 1, 0.36, 1] }}><svg aria-hidden className="pointer-events-none absolute right-full top-8 h-8 w-[62px] overflow-visible" viewBox="0 0 62 32"><path d="M0 16 C20 16, 35 16, 62 16" fill="none" stroke={color} strokeDasharray="2 5" strokeLinecap="round" strokeOpacity="0.75" strokeWidth="2" /><circle cx="4" cy="16" fill="white" r="4" stroke={color} strokeWidth="2" /><circle cx="58" cy="16" fill="white" r="4" stroke={color} strokeWidth="2" /></svg><div className="rounded-[14px] border border-[#D9D8DC] bg-white p-3.5 shadow-[0_14px_34px_rgba(25,25,30,0.16)]"><div className="mb-3 flex items-center gap-2 border-b border-[#ECEBED] pb-2"><span className="grid h-7 w-7 place-items-center rounded-[8px] text-white" style={{ backgroundColor: color }}><Icon size={15} /></span><div className="min-w-0 flex-1"><p className="text-[12px] font-semibold text-[#333337]">{module.title}</p><p className="truncate text-[9px] text-[#85858B]">Expanded details · {module.sourceFileIds.length} sources</p></div><button aria-label={`Close ${module.title} details`} className="grid h-6 w-6 place-items-center rounded text-[#85858B] hover:bg-[#F1F0F1]" onClick={onToggle} type="button"><X size={14} /></button></div>{children}</div></motion.div>}</AnimatePresence>
  </motion.section>;
}

export default function SummaryCardNode({ id, data, selected }: NodeProps<SummaryCardNodeType>) {
  const updateNodeInternals = useUpdateNodeInternals();
  const [editing, setEditing] = useState(false);
  const [title, setTitle] = useState(data.cluster.name);
  const [menu, setMenu] = useState(false);
  const [expense, setExpense] = useState({ category: '', amount: '' });
  const [newItem, setNewItem] = useState('');
  const dashboard = data.dashboard ?? {};
  const fallback = fallbackPlan(data.files, data.cluster);
  const plan = data.dashboardPlan?.modules.every((module) => Boolean(module.visual) && Array.isArray(module.interactions) && Boolean(module.compact)) ? data.dashboardPlan : fallback;
  const HeaderIcon = iconForPlan[plan.headerIcon] ?? SparklesIcon;
  const Sparkles = HeaderIcon;
  const openModule = dashboard.expandedSection;
  const costs = data.files.flatMap((file) => file.entities.costs);
  const previewBudget = data.files.find((file) => file.smartPreview.type === 'budget')?.smartPreview.displayData ?? {};
  const initialRows = useMemo<DashboardBudgetRow[]>(() => {
    const rows = Array.isArray(previewBudget.rows) ? previewBudget.rows as Array<{ category?: string; estimate?: number }> : costs.map((cost) => ({ category: cost.label, estimate: cost.amount }));
    return rows.map((row, index) => ({ id: `source-${index}`, category: row.category || 'Other', estimate: typeof row.estimate === 'number' ? row.estimate : 0 }));
  }, [costs, previewBudget]);
  const budgetRows = dashboard.budgetRows ?? initialRows;
  const checklistFile = data.files.find((file) => file.smartPreview.type === 'checklist') ?? data.files.find((file) => file.entities.tasks.length);
  const initialItems = useMemo<DashboardPackingItem[]>(() => {
    const raw = checklistFile && Array.isArray(checklistFile.smartPreview.displayData.items) ? checklistFile.smartPreview.displayData.items as Array<{ text?: string; checked?: boolean }> : checklistFile?.entities.tasks.map((task) => ({ text: task.item, checked: task.completed })) ?? [];
    return raw.map((item, index) => ({ id: `source-${index}`, text: item.text || 'Untitled item', checked: Boolean(item.checked), source: 'file' }));
  }, [checklistFile]);
  const items = dashboard.packingItems ?? initialItems;
  const locations: DashboardLocation[] = data.files.flatMap((file) => file.entities.locations.map((location) => ({ ...location, fileName: file.fileName }))).filter((location, index, all) => all.findIndex((item) => item.name === location.name) === index);
  const total = budgetRows.reduce((sum, row) => sum + row.estimate, 0) || 1;
  const actual = budgetRows.reduce((sum, row) => sum + (row.actual ?? row.estimate), 0);
  const packed = items.filter((item) => item.checked).length;
  const currency = value(previewBudget, 'currency') || costs[0]?.currency || 'USD';
  const patch = (next: Partial<DashboardState>) => emit('aether:dashboard-state', { summaryId: id, patch: next });
  const toggle = (module: DashboardModule) => patch({ expandedSection: openModule === module.id ? undefined : module.id as DashboardState['expandedSection'] });
  const focus = (module: DashboardModule, active: boolean) => emit('aether:summary-section-focus', active ? relationshipFor(module.kind) : null);
  const sourceFiles = (module: DashboardModule) => data.files.filter((file) => module.sourceFileIds.includes(file.id));
  useEffect(() => { requestAnimationFrame(() => updateNodeInternals(id)); }, [id, openModule, updateNodeInternals]);

  const content = (module: DashboardModule) => {
    const moduleSources = sourceFiles(module);
    if (module.visual === 'route-rail') {
      const dates = data.files.flatMap((file) => file.entities.dates.map((date) => ({ ...date, file }))).sort((left, right) => left.date.localeCompare(right.date)).slice(0, 5);
      return <div className="space-y-3"><div className="rounded-[9px] border border-[#E3E7EB] bg-[#F8FBFE] px-3 py-2.5"><div className="flex items-center justify-between"><div><b className="text-[16px] text-[#303034]">{module.compact.primary}</b><span className="block text-[9px] text-[#73737A]">Departure</span></div><div className="mx-3 flex flex-1 items-center gap-1 text-[#66727E]"><span className="h-px flex-1 border-t border-dashed border-[#AFB8C1]" /><Plane size={19} /><span className="h-px flex-1 border-t border-dashed border-[#AFB8C1]" /></div><div className="text-right"><b className="text-[16px] text-[#303034]">{module.compact.secondary}</b><span className="block text-[9px] text-[#73737A]">Arrival</span></div></div>{module.compact.tertiary && <p className="mt-2 flex items-center gap-1.5 border-t border-[#E4E9ED] pt-2 text-[10px] text-[#5E6268]"><CarFront size={13} className="text-[#4A90D9]" />{module.compact.tertiary}</p>}</div><div className="relative space-y-2 border-l-2 border-[#D5E5F4] pl-4">{dates.map((date) => <button className="nodrag relative block w-full rounded-[7px] bg-[#FAFAFB] px-2.5 py-2 text-left hover:bg-[#F2F7FC]" key={`${date.file.id}-${date.label}`} onClick={() => emit('aether:focus-source-file', date.file.id)} type="button"><span className="absolute -left-[21px] top-3 h-2.5 w-2.5 rounded-full border-2 border-white bg-[#4A90D9] shadow" /><b className="text-[10px] text-[#3C3C41]">{date.label}</b><span className="ml-2 text-[9px] text-[#74747B]">{date.display}</span><span className="block truncate text-[9px] text-[#94949A]">from {date.file.fileName}</span></button>)}</div>{module.interactions.includes('copy') && <button className="nodrag flex items-center gap-1 rounded-[6px] border border-[#DCE4EA] px-2 py-1.5 text-[10px] text-[#55718D] hover:bg-[#F3F8FC]" onClick={() => { void navigator.clipboard.writeText(`${module.compact.primary} → ${module.compact.secondary}\n${module.compact.tertiary}`); emit('aether:toast', 'Journey details copied'); }} type="button"><Clipboard size={12} />Copy journey</button>}</div>;
    }
    if (module.visual === 'ring-metric') return <div className="mt-3"><div className="flex items-center gap-3"><div className="relative grid h-16 w-16 place-items-center"><svg className="h-16 w-16 -rotate-90"><circle cx="32" cy="32" fill="none" r="25" stroke="#E9E9E7" strokeWidth="8" /><motion.circle animate={{ stroke: actual > total ? '#EA4335' : '#34A853', strokeDashoffset: 157 * (1 - Math.min(1, actual / total)) }} cx="32" cy="32" fill="none" r="25" strokeDasharray="157" strokeLinecap="round" strokeWidth="8" /></svg><span className="absolute text-[10px] font-semibold">{money(actual, currency)}</span></div><p className="text-[10px] text-[#66666C]">{actual > total ? `${money(actual - total, currency)} over budget` : `${money(total - actual, currency)} remaining`}</p></div><div className="mt-3 space-y-1">{budgetRows.map((row) => <div className="grid grid-cols-[1fr_58px_58px] gap-1 text-[10px]" key={row.id}><span>{row.category}</span><span className="text-right text-[#77777D]">{money(row.estimate, currency)}</span>{module.interactions.includes('edit-values') ? <input className="nodrag min-w-0 bg-transparent text-right outline-none" onChange={(event) => patch({ budgetRows: budgetRows.map((item) => item.id === row.id ? { ...item, actual: event.target.value ? Number(event.target.value) : undefined } : item) })} placeholder="—" type="number" value={row.actual ?? ''} /> : <span className="text-right">{row.actual === undefined ? '—' : money(row.actual, currency)}</span>}</div>)}</div>{module.interactions.includes('add-item') && <div className="mt-2 flex gap-1"><input className="nodrag min-w-0 flex-1 rounded border px-2 py-1 text-[10px]" onChange={(event) => setExpense((current) => ({ ...current, category: event.target.value }))} placeholder="Expense" value={expense.category} /><input className="nodrag w-16 rounded border px-2 py-1 text-[10px]" onChange={(event) => setExpense((current) => ({ ...current, amount: event.target.value }))} placeholder="Amount" type="number" value={expense.amount} /><button className="nodrag grid h-6 w-6 place-items-center rounded bg-[#34A853] text-white" onClick={() => { if (expense.category && Number(expense.amount)) { patch({ budgetRows: [...budgetRows, { id: crypto.randomUUID(), category: expense.category, estimate: Number(expense.amount) }] }); setExpense({ category: '', amount: '' }); } }} type="button"><Plus size={13} /></button></div>}{module.interactions.includes('export') && <button className="nodrag mt-2 flex items-center gap-1 text-[10px] text-[#77777D]" onClick={() => emit('aether:export-budget', { currency, rows: budgetRows })} type="button"><Download size={12} />Export CSV</button>}</div>;
    if (module.visual === 'progress') return <div className="mt-3"><p className="text-[11px] font-medium">{packed} / {items.length} complete</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#E7E5E9]"><motion.div animate={{ width: `${items.length ? packed / items.length * 100 : 0}%` }} className="h-full bg-[#9B72CF]" /></div><div className="mt-3 space-y-1">{items.map((item) => <button className={`nodrag flex w-full items-center gap-2 text-left text-[10px] ${item.checked ? 'text-[#8A8A90]' : 'text-[#46464B]'}`} disabled={!module.interactions.includes('toggle-item')} key={item.id} onClick={() => patch({ packingItems: items.map((entry) => entry.id === item.id ? { ...entry, checked: !entry.checked } : entry) })} type="button"><span className={`grid h-4 w-4 place-items-center rounded border ${item.checked ? 'border-[#34A853] bg-[#34A853] text-white' : 'border-[#9B9BA0]'}`}>{item.checked && <Check size={11} />}</span><span className={item.checked ? 'line-through' : ''}>{item.text}</span></button>)}</div>{module.interactions.includes('add-item') && <input className="nodrag mt-3 w-full border-b bg-transparent py-1 text-[10px] outline-none" onChange={(event) => setNewItem(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && newItem.trim()) { patch({ packingItems: [...items, { id: crypto.randomUUID(), text: newItem.trim(), checked: false, source: 'user' }] }); setNewItem(''); } }} placeholder="Add item…" value={newItem} />}</div>;
    if (module.visual === 'pin-map') return <div className="mt-3"><InteractiveMap expanded locations={locations} onLocationFocus={(location) => emit('aether:focus-source-file', data.files.find((file) => file.fileName === location.fileName)?.id ?? '')} onOpenDirections={(place) => void window.aether.openExternal(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place)}`)} suggestions={dashboard.aiCache?.map ?? []} /></div>;
    if (module.visual === 'milestone-list') { const dates = data.files.flatMap((file) => file.entities.dates.map((date) => ({ ...date, file }))).sort((left, right) => left.date.localeCompare(right.date)); return <div className="mt-3 space-y-2 border-l-2 border-[#C9DCEF] pl-3">{dates.slice(0, 7).map((date) => <button className="nodrag block text-left text-[10px]" key={`${date.file.id}-${date.label}`} onClick={() => emit('aether:focus-source-file', date.file.id)} type="button"><b className="text-[#3A3A3F]">{date.display}</b><span className="ml-2 text-[#77777D]">{date.label}</span></button>)}</div>; }
    return <div className="mt-3"><p className="text-[10px] leading-4 text-[#626268]">{module.summary}</p><div className="mt-2 space-y-1">{moduleSources.map((file) => <button className="nodrag flex w-full items-center gap-1.5 rounded px-1 py-1 text-left text-[10px] text-[#56565C] hover:bg-[#F5F4F2]" key={file.id} onClick={() => emit('aether:focus-source-file', file.id)} type="button"><FileText size={12} />{file.title}</button>)}</div></div>;
  };

  return <motion.article animate={{ opacity: 1, x: 0 }} className={`w-[320px] rounded-[16px] border bg-white p-3 shadow-[0_5px_18px_rgba(0,0,0,0.12)] ${selected ? 'border-[#4A90D9]' : 'border-[#D5D5D9]'}`} initial={{ opacity: 0, x: 80 }} transition={{ delay: data.assemblyDelay ?? 1.2, duration: 0.36 }}><header className="relative mb-3 flex items-start gap-2"><span className="grid h-9 w-9 place-items-center rounded-[10px] bg-[#F2ECFB] text-[#7B57A9]"><Sparkles size={19} /></span><div className="min-w-0 flex-1">{editing ? <input autoFocus className="nodrag w-full rounded bg-[#F4F3F1] px-1 text-[19px] font-semibold outline-none" onBlur={() => { if (title.trim()) emit('aether:rename-cluster', { summaryId: id, name: title.trim() }); setEditing(false); }} onChange={(event) => setTitle(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') event.currentTarget.blur(); if (event.key === 'Escape') setEditing(false); }} value={title} /> : <h2 className="truncate text-[21px] font-semibold tracking-[-0.03em] text-[#29292C]" onDoubleClick={() => setEditing(true)}>{plan.title || data.cluster.name}</h2>}<p className="mt-0.5 text-[11px] text-[#77777D]">{plan.subtitle || data.cluster.dateRange}</p></div><button className="nodrag grid h-7 w-7 place-items-center rounded text-[#77777D] hover:bg-[#F2F2F4]" onClick={() => setMenu((current) => !current)} type="button"><MoreHorizontal size={18} /></button>{menu && <div className="absolute right-0 top-8 z-30 w-40 rounded border bg-white p-1 shadow-lg"><button className="nodrag block w-full rounded px-2 py-1.5 text-left text-[10px] hover:bg-[#F5F4F2]" onClick={() => { setMenu(false); setEditing(true); }} type="button">Rename</button><button className="nodrag flex w-full items-center gap-1 rounded px-2 py-1.5 text-left text-[10px] hover:bg-[#F5F4F2]" onClick={() => emit('aether:export-summary', { cluster: { ...data.cluster, name: plan.title || data.cluster.name }, files: data.files, budgetRows, packingItems: items, locations })} type="button"><Download size={12} />Export summary</button><button className="nodrag flex w-full items-center gap-1 rounded px-2 py-1.5 text-left text-[10px] text-[#C43E34] hover:bg-[#FFF0EE]" onClick={() => emit('aether:remove-cluster', id)} type="button"><X size={12} />Remove cluster</button></div>}</header><div className="space-y-2">{plan.modules.map((module) => <ModuleShell key={module.id} module={module} onHover={(active) => focus(module, active)} onToggle={() => toggle(module)} open={openModule === module.id}>{content(module)}</ModuleShell>)}</div><footer className="mt-3 flex justify-center"><button className="nodrag flex items-center gap-1.5 rounded-full border border-[#E2E2E5] bg-[#FAFAFB] px-3 py-1.5 text-[10px] font-medium text-[#6F6F74]" onClick={() => emit('aether:highlight-sources', data.files.map((file) => file.id))} type="button"><Sparkles size={13} />Generated from {data.files.length} files</button></footer></motion.article>;
}
