import { AnimatePresence, motion } from 'framer-motion';
import { Handle, Position, useUpdateNodeInternals, type Node, type NodeProps } from '@xyflow/react';
import { BookOpen, CarFront, Check, CheckSquare, ChevronDown, Clipboard, Download, FileText, ListChecks, Map, MapPin, MoreHorizontal, Plane, Plus, Sparkles as SparklesIcon, Wallet, X } from 'lucide-react';
import { useEffect, useMemo, useState, type ComponentType } from 'react';

import type { AnalyzedFile, DashboardBudgetRow, DashboardModule, DashboardModuleKind, DashboardPackingItem, DashboardPlan, DashboardState, RelationshipType, SuggestedCluster } from '../../../../shared/types';
import InteractiveMap, { type DashboardLocation } from './InteractiveMap';

export type SummaryCardNodeData = { cluster: SuggestedCluster; files: AnalyzedFile[]; dashboard?: DashboardState; dashboardPlan?: DashboardPlan; assemblyDelay?: number };
export type SummaryCardNodeType = Node<SummaryCardNodeData, 'summaryCard'>;

const COLORS: Record<RelationshipType, string> = { dates: '#4A90D9', cost: '#34A853', place: '#EA4335', tasks: '#9B72CF' };
const iconForKind: Record<DashboardModuleKind, ComponentType<{ size?: number; strokeWidth?: number }>> = { overview: SparklesIcon, timeline: Plane, budget: Wallet, checklist: CheckSquare, map: Map, tasks: ListChecks, topics: BookOpen, resources: FileText, results: SparklesIcon };
const iconForPlan = { sparkles: SparklesIcon, plane: Plane, wallet: Wallet, 'check-square': CheckSquare, map: Map, 'list-checks': ListChecks, 'book-open': BookOpen, 'file-text': FileText } as const;
const relationshipFor = (kind: DashboardModuleKind): RelationshipType | null => ({ timeline: 'dates', budget: 'cost', checklist: 'tasks', tasks: 'tasks', map: 'place' } as Partial<Record<DashboardModuleKind, RelationshipType>>)[kind] ?? null;
const colorFor = (module: DashboardModule) => module.accent === 'dates' ? COLORS.dates : module.accent === 'cost' ? COLORS.cost : module.accent === 'place' ? COLORS.place : module.accent === 'tasks' ? COLORS.tasks : '#9B72CF';
const value = (data: Record<string, unknown>, key: string) => typeof data[key] === 'string' ? data[key] : '';
const money = (amount: number, currency: string) => new Intl.NumberFormat('en-US', { style: 'currency', currency, maximumFractionDigits: 0 }).format(amount);
const emit = (name: string, detail: unknown) => window.dispatchEvent(new CustomEvent(name, { detail }));
const dataValue = (files: AnalyzedFile[], key: string) => files.map((file) => value(file.smartPreview.displayData, key)).find(Boolean) ?? '';
type ModuleWithoutCompact = Omit<DashboardModule, 'compact'>;

function compactFor(module: ModuleWithoutCompact, files: AnalyzedFile[]) {
  if (module.visual === 'route-rail') return { primary: dataValue(files, 'origin') || files.flatMap((file) => file.entities.dates)[0]?.display || 'Start', secondary: dataValue(files, 'destination') || files.flatMap((file) => file.entities.dates).at(-1)?.display || 'Next', tertiary: dataValue(files, 'checkIn') || 'Next step' };
  if (module.visual === 'ring-metric') return { primary: dataValue(files, 'total') || 'Budget', secondary: 'Tracked', tertiary: `${files.flatMap((file) => file.entities.costs).length} items` };
  if (module.visual === 'progress') { const tasks = files.flatMap((file) => file.entities.tasks); return { primary: `${tasks.filter((task) => task.completed).length} / ${tasks.length}`, secondary: 'complete', tertiary: '' }; }
  if (module.visual === 'pin-map') { const locations = files.flatMap((file) => file.entities.locations); return { primary: locations[0]?.name ?? '', secondary: locations[1]?.name ?? '', tertiary: locations[2]?.name ?? '' }; }
  return { primary: module.title, secondary: `${module.sourceFileIds.length} source files`, tertiary: '' };
}

function fallbackPlan(files: AnalyzedFile[], cluster: SuggestedCluster): DashboardPlan {
  const modules: ModuleWithoutCompact[] = [{ id: 'overview', kind: 'overview', title: cluster.category === 'education' ? 'Key concepts' : 'Overview', summary: files.map((file) => file.summary).slice(0, 2).join(' '), icon: 'sparkles', accent: 'neutral', visual: 'key-points', interactions: ['expand', 'focus-source'], sourceFileIds: files.map((file) => file.id) }];
  if (files.some((file) => file.entities.dates.length)) modules.push({ id: 'timeline', kind: 'timeline', title: cluster.category === 'travel' ? 'Journey' : 'Timeline', summary: 'Important dates synthesized from your source files.', icon: 'plane', accent: 'dates', visual: cluster.category === 'travel' ? 'route-rail' : 'milestone-list', interactions: ['expand', 'focus-source', 'copy'], sourceFileIds: files.filter((file) => file.entities.dates.length).map((file) => file.id) });
  if (files.some((file) => file.entities.costs.length)) modules.push({ id: 'budget', kind: 'budget', title: 'Budget', summary: 'Editable amounts grounded in the files you added.', icon: 'wallet', accent: 'cost', visual: 'ring-metric', interactions: ['expand', 'edit-values', 'export'], sourceFileIds: files.filter((file) => file.entities.costs.length).map((file) => file.id) });
  if (files.some((file) => file.entities.tasks.length)) modules.push({ id: 'tasks', kind: 'tasks', title: cluster.category === 'travel' ? 'Packing' : 'Tasks', summary: 'Track the actionable items Aether found.', icon: 'list-checks', accent: 'tasks', visual: 'progress', interactions: ['expand', 'toggle-item', 'add-item'], sourceFileIds: files.filter((file) => file.entities.tasks.length).map((file) => file.id) });
  if (files.some((file) => file.entities.locations.length)) modules.push({ id: 'map', kind: 'map', title: cluster.category === 'travel' ? 'Map' : 'Places', summary: 'Places mentioned across this workspace.', icon: 'map', accent: 'place', visual: 'pin-map', interactions: ['expand', 'focus-source', 'open-map'], sourceFileIds: files.filter((file) => file.entities.locations.length).map((file) => file.id) });
  return { title: cluster.name, subtitle: cluster.dateRange, category: cluster.category, headerIcon: cluster.category === 'travel' ? 'map' : cluster.category === 'education' ? 'book-open' : 'sparkles', headerAccent: cluster.category === 'travel' ? 'place' : 'neutral', modules: modules.map((module) => ({ ...module, compact: compactFor(module, files) })) };
}

function CompactPreview({ module, color }: { module: DashboardModule; color: string }) {
  const compact = module.compact;

  if (module.visual === 'route-rail') return (
    <div className="mt-3">
      <div className="flex items-center justify-between rounded-[10px] border border-[#E8E7E4] bg-[linear-gradient(135deg,#FFFFFF_0%,#FAFAF9_100%)] px-3 py-2.5 shadow-[inset_0_1px_0_rgba(255,255,255,0.95),0_1px_2px_rgba(31,31,36,0.03)]">
        <span><b className="block text-[14px] leading-none tracking-[-0.03em] text-[#26262A]">{compact.primary}</b><small className="mt-1 block text-[8px] font-medium uppercase tracking-[0.08em] text-[#929198]">Depart</small></span>
        <div className="mx-3 flex flex-1 items-center gap-1.5 text-[#68727D]"><span className="h-px flex-1 border-t border-dashed border-[#C3C4C6]" /><span className="grid h-6 w-6 place-items-center rounded-full bg-[#EEF5FC] text-[#4A90D9]"><Plane size={14} strokeWidth={2.4} /></span><span className="h-px flex-1 border-t border-dashed border-[#C3C4C6]" /></div>
        <span className="text-right"><b className="block text-[14px] leading-none tracking-[-0.03em] text-[#26262A]">{compact.secondary}</b><small className="mt-1 block text-[8px] font-medium uppercase tracking-[0.08em] text-[#929198]">Arrive</small></span>
      </div>
      {compact.tertiary && <p className="mt-2 flex items-center gap-1.5 px-0.5 text-[10px] font-medium text-[#67676E]"><span className="grid h-4 w-4 place-items-center rounded-[5px] bg-[#F1F6FC]" style={{ color }}><CarFront size={11} strokeWidth={2.2} /></span>{compact.tertiary}</p>}
    </div>
  );

  if (module.visual === 'ring-metric') return (
    <div className="mt-3 flex items-center gap-3.5">
      <div className="relative grid h-[62px] w-[62px] place-items-center rounded-full bg-[radial-gradient(circle_at_50%_45%,#FFFFFF_0%,#FBFBFA_62%,#F0EFEC_100%)] shadow-[inset_0_1px_2px_rgba(27,27,31,0.05)]">
        <svg className="absolute h-[62px] w-[62px] -rotate-90"><circle cx="31" cy="31" fill="none" r="25" stroke="#ECEBE8" strokeWidth="7" /><circle cx="31" cy="31" fill="none" r="25" stroke={color} strokeDasharray="117 157" strokeLinecap="round" strokeWidth="7" /></svg>
        <b className="text-center text-[10px] font-semibold tracking-[-0.04em] text-[#313137]">{compact.primary}</b>
      </div>
      <div className="min-w-0 space-y-1.5 text-[10px]"><p className="flex items-center gap-1.5 font-medium text-[#4E4E54]"><i className="h-2 w-2 rounded-full shadow-[0_1px_2px_rgba(0,0,0,0.16)]" style={{ backgroundColor: color }} />{compact.secondary}</p><p className="flex items-center gap-1.5 text-[#85848A]"><i className="h-2 w-2 rounded-full bg-[#C7C5C0]" />{compact.tertiary}</p></div>
    </div>
  );

  if (module.visual === 'progress') {
    const match = compact.primary.match(/(\d+)\s*\/\s*(\d+)/);
    const progress = match ? Math.min(100, Number(match[1]) / Number(match[2]) * 100) : 55;
    return <div className="mt-3"><p className="text-[11px] text-[#66666D]"><b className="mr-1 text-[23px] leading-none tracking-[-0.06em] text-[#2D2D32]">{compact.primary}</b>{compact.secondary}</p><div className="mt-2.5 h-[7px] overflow-hidden rounded-full bg-[#EAE8ED] shadow-[inset_0_1px_2px_rgba(29,29,33,0.08)]"><motion.div animate={{ width: `${progress}%` }} className="relative h-full rounded-full" style={{ background: `linear-gradient(90deg, ${color}, ${color}CC)` }} transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}><span className="absolute right-0 top-1/2 h-2.5 w-2.5 -translate-y-1/2 rounded-full border border-white/70 bg-white/55 shadow-[0_1px_3px_rgba(0,0,0,0.2)]" /></motion.div></div></div>;
  }

  if (module.visual === 'pin-map') return <div className="relative mt-3 h-[76px] overflow-hidden rounded-[10px] border border-[#E6E2D8] bg-[#F0ECE4] shadow-[inset_0_1px_0_rgba(255,255,255,.72)]" style={{ backgroundImage: 'linear-gradient(28deg, transparent 42%, rgba(255,255,255,.88) 43%, rgba(255,255,255,.88) 46%, transparent 47%), linear-gradient(112deg, transparent 48%, rgba(255,255,255,.78) 49%, rgba(255,255,255,.78) 52%, transparent 53%), radial-gradient(circle at 80% 10%, rgba(255,255,255,.72), transparent 34%)' }}><span className="absolute inset-x-0 top-0 h-5 bg-gradient-to-b from-white/45 to-transparent" /><MapPin className="absolute left-[21%] top-[31%] drop-shadow-[0_2px_2px_rgba(70,35,20,.22)]" fill={color} size={21} style={{ color }} /><MapPin className="absolute left-[50%] top-[48%] drop-shadow-[0_2px_2px_rgba(70,35,20,.22)]" fill={color} size={18} style={{ color }} /><MapPin className="absolute right-[19%] top-[18%] drop-shadow-[0_2px_2px_rgba(70,35,20,.22)]" fill={color} size={21} style={{ color }} /><span className="absolute bottom-1.5 left-2.5 text-[8px] font-medium text-[#57545A]">{compact.primary}</span><span className="absolute bottom-1.5 left-[42%] text-[8px] font-medium text-[#57545A]">{compact.secondary}</span><span className="absolute right-2.5 top-1.5 text-[8px] font-medium text-[#57545A]">{compact.tertiary}</span></div>;

  if (module.visual === 'key-points') {
    const points = module.summary.split(/(?<=[.!?])\s+/).filter(Boolean).slice(0, 2);
    return <div className="mt-3 overflow-hidden rounded-[10px] border border-[#EAE7EF] bg-[linear-gradient(135deg,#FBF9FE_0%,#FFFFFF_100%)] px-3 py-2.5 shadow-[inset_0_1px_0_rgba(255,255,255,.9)]"><p className="mb-2 text-[8px] font-semibold uppercase tracking-[0.12em] text-[#876BA5]">Workspace brief</p><div className="space-y-1.5">{(points.length ? points : [compact.primary, compact.secondary]).map((point, index) => <p className="flex gap-2 text-[10px] leading-[1.45] text-[#5D5963]" key={`${point}-${index}`}><span className="mt-[5px] h-1.5 w-1.5 shrink-0 rounded-full shadow-[0_1px_2px_rgba(55,32,75,.25)]" style={{ backgroundColor: color }} />{point}</p>)}</div></div>;
  }

  if (module.visual === 'stat-grid') return <div className="mt-3 grid grid-cols-3 overflow-hidden rounded-[10px] border border-[#E8E7E9] bg-[#FCFCFC] shadow-[inset_0_1px_0_rgba(255,255,255,.9)]">{[compact.primary, compact.secondary, compact.tertiary].map((stat, index) => <div className={`min-w-0 px-2 py-2.5 text-center ${index ? 'border-l border-[#ECEBED]' : ''}`} key={stat || index}><b className="block truncate text-[11px] tracking-[-0.025em] text-[#35353B]">{stat || '—'}</b><span className="mt-1 block text-[7px] font-medium uppercase tracking-[0.08em] text-[#96959B]">{['Current', 'Tracked', 'Next'][index]}</span></div>)}</div>;

  if (module.visual === 'priority-stack') return <div className="mt-3 space-y-1.5">{[compact.primary, compact.secondary, compact.tertiary].filter(Boolean).map((label, index) => <div className="flex items-center gap-2 rounded-[8px] border border-[#ECEAED] bg-white px-2.5 py-1.5 shadow-[0_1px_2px_rgba(25,25,30,.025)]" key={label} style={{ marginLeft: `${index * 5}px` }}><span className="grid h-4 w-4 shrink-0 place-items-center rounded-full text-[8px] font-semibold text-white" style={{ backgroundColor: color, opacity: 1 - index * 0.16 }}>{index + 1}</span><span className="truncate text-[10px] font-medium text-[#55535B]">{label}</span></div>)}</div>;

  if (module.visual === 'calendar-strip') return <div className="mt-3 grid grid-cols-3 gap-1.5">{[compact.primary, compact.secondary, compact.tertiary].map((date, index) => <div className="rounded-[9px] border border-[#E8E7EA] bg-[linear-gradient(180deg,#FFFFFF,#FAFAFA)] px-1.5 py-2 text-center shadow-[inset_0_1px_0_rgba(255,255,255,.95)]" key={date || index}><span className="block text-[7px] font-semibold uppercase tracking-[0.1em] text-[#99979D]">{['Start', 'Focus', 'Due'][index]}</span><b className="mt-1 block truncate text-[10px] tracking-[-0.02em] text-[#3E3D43]">{date || '—'}</b></div>)}</div>;

  if (module.visual === 'activity-stream') return <div className="mt-3 space-y-2 border-l-2 pl-3" style={{ borderColor: `${color}40` }}>{[compact.primary, compact.secondary, compact.tertiary].filter(Boolean).map((event, index) => <div className="relative text-[10px] text-[#5F5E65]" key={event}><span className="absolute -left-[18px] top-[4px] h-2 w-2 rounded-full border-2 border-white shadow-[0_1px_3px_rgba(0,0,0,.14)]" style={{ backgroundColor: color }} />{event}</div>)}</div>;

  if (module.visual === 'comparison-bars') return <div className="mt-3 space-y-2">{[compact.primary, compact.secondary, compact.tertiary].filter(Boolean).map((label, index) => <div key={label}><div className="mb-1 flex justify-between text-[9px] text-[#65646B]"><span className="truncate">{label}</span><span>{[82, 58, 36][index]}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-[#ECEBED]"><div className="h-full rounded-full" style={{ width: `${[82, 58, 36][index]}%`, backgroundColor: color, opacity: 1 - index * 0.17 }} /></div></div>)}</div>;

  if (module.visual === 'source-list') return <div className="mt-3 space-y-1.5">{[compact.primary, compact.secondary, compact.tertiary].filter(Boolean).map((source, index) => <div className="flex items-center gap-2 rounded-[8px] bg-[#FAFAFB] px-2.5 py-1.5 text-[10px] text-[#5C5B62]" key={source}><FileText size={12} style={{ color }} /><span className="truncate">{source}</span><span className="ml-auto text-[8px] text-[#A09FA4]">{index + 1}</span></div>)}</div>;

  return <div className="mt-3 rounded-[9px] border border-[#EEEBE6] bg-[#FBFAF8] px-3 py-2.5 text-[10px] leading-4 text-[#6A696F]"><b className="block font-semibold text-[#38383E]">{compact.primary}</b><span>{[compact.secondary, compact.tertiary].filter(Boolean).join(' · ')}</span></div>;
}

function ModuleShell({ module, open, onToggle, onHover, children }: { module: DashboardModule; open: boolean; onToggle: () => void; onHover: (active: boolean) => void; children: React.ReactNode }) {
  const [isOpen, setIsOpen] = useState(false);
  const Icon = iconForPlan[module.icon] ?? iconForKind[module.kind];
  const relationship = relationshipFor(module.kind);
  const color = colorFor(module);
  useEffect(() => setIsOpen(open), [open]);
  return <motion.section layout className="group relative overflow-visible rounded-[13px] border border-[#E2E1E4] bg-[linear-gradient(145deg,#FFFFFF_0%,#FCFCFC_100%)] px-3.5 py-3 shadow-[inset_0_1px_0_rgba(255,255,255,.96),0_1px_2px_rgba(25,25,29,.035)] transition-[border-color,box-shadow,transform] duration-200 hover:-translate-y-px hover:border-[#D7D5D9] hover:shadow-[inset_0_1px_0_rgba(255,255,255,1),0_7px_16px_rgba(25,25,29,.075)]" onMouseEnter={() => onHover(true)} onMouseLeave={() => onHover(false)} transition={{ duration: 0.22 }}>
    {relationship && <><Handle className="!h-[8px] !w-[8px] !border-0 !bg-transparent !opacity-0" id={`summary-${relationship}`} position={Position.Left} style={{ top: '50%' }} type="target" /><span aria-hidden className="pointer-events-none absolute left-[-11px] top-1/2 grid h-[19px] w-[19px] -translate-y-1/2 place-items-center rounded-full border-[3px] border-white shadow-[0_2px_7px_rgba(24,24,30,0.16)] transition-transform duration-200 group-hover:scale-110" style={{ backgroundColor: color }}><span className="h-1.5 w-1.5 rounded-full bg-white shadow-[0_1px_1px_rgba(0,0,0,.15)]" /></span></>}
    <button aria-expanded={isOpen} className="nodrag flex w-full items-center gap-2.5 rounded-[8px] text-left outline-none focus-visible:ring-2 focus-visible:ring-[#4A90D9]/40" onClick={onToggle} type="button"><span className="grid h-6 w-6 place-items-center rounded-full text-white shadow-[inset_0_1px_1px_rgba(255,255,255,.36),0_2px_4px_rgba(30,30,35,.16)]" style={{ background: `linear-gradient(145deg, ${color}, ${color}D9)` }}><Icon size={14} strokeWidth={2.5} /></span><span className="flex-1 text-[12px] font-semibold tracking-[-0.01em] text-[#323238]">{module.title}</span><span className="grid h-5 w-5 place-items-center rounded-full text-[#8D8D94] transition-colors group-hover:bg-[#F1F0F2] group-hover:text-[#5B5B61]"><ChevronDown className={`transition-transform duration-300 ${isOpen ? 'rotate-180' : ''}`} size={15} /></span></button>
    <CompactPreview color={color} module={module} />
    <AnimatePresence>{isOpen && <motion.div animate={{ opacity: 1, scale: 1, x: 0 }} className="nodrag absolute left-[calc(100%+70px)] top-0 z-50 w-[350px]" exit={{ opacity: 0, scale: 0.98, x: -8 }} initial={{ opacity: 0, scale: 0.98, x: -12 }} transition={{ duration: 0.26, ease: [0.22, 1, 0.36, 1] }}><svg aria-hidden className="pointer-events-none absolute right-full top-8 h-8 w-[70px] overflow-visible" viewBox="0 0 70 32"><path d="M0 16 C22 16, 42 16, 70 16" fill="none" stroke={color} strokeDasharray="2 5" strokeLinecap="round" strokeOpacity="0.78" strokeWidth="2" /><circle cx="4" cy="16" fill="white" r="4" stroke={color} strokeWidth="2" /><circle cx="66" cy="16" fill="white" r="4" stroke={color} strokeWidth="2" /></svg><div className="overflow-hidden rounded-[17px] border border-[#DCDADF] bg-[linear-gradient(145deg,#FFFFFF_0%,#FCFCFD_100%)] p-4 shadow-[0_20px_48px_rgba(25,25,30,0.18),0_2px_5px_rgba(25,25,30,0.06)]"><div className="mb-3.5 flex items-center gap-2.5 border-b border-[#ECEBED] pb-3"><span className="grid h-8 w-8 place-items-center rounded-[10px] text-white shadow-[inset_0_1px_1px_rgba(255,255,255,.4),0_2px_4px_rgba(25,25,30,.15)]" style={{ background: `linear-gradient(145deg, ${color}, ${color}D9)` }}><Icon size={16} /></span><div className="min-w-0 flex-1"><p className="text-[13px] font-semibold tracking-[-0.02em] text-[#303036]">{module.title}</p><p className="mt-0.5 truncate text-[9px] font-medium tracking-[0.02em] text-[#909096]">EXPANDED DETAILS · {module.sourceFileIds.length} SOURCES</p></div><button aria-label={`Close ${module.title} details`} className="grid h-7 w-7 place-items-center rounded-full text-[#85858B] transition hover:bg-[#F0EFF2] hover:text-[#494950]" onClick={onToggle} type="button"><X size={14} /></button></div>{children}</div></motion.div>}</AnimatePresence>
  </motion.section>;
}

export default function SummaryCardNode({ id, data, selected }: NodeProps<SummaryCardNodeType>) {
  const updateNodeInternals = useUpdateNodeInternals();
  const [editing, setEditing] = useState(false);
  const [title, setTitle] = useState(data.cluster.name);
  const [menu, setMenu] = useState(false);
  const [expense, setExpense] = useState({ category: '', amount: '' });
  const [newItem, setNewItem] = useState('');
  const dashboard = data.dashboard ?? {};
  const fallback = fallbackPlan(data.files, data.cluster);
  const plan = data.dashboardPlan?.modules.every((module) => Boolean(module.visual) && Array.isArray(module.interactions) && Boolean(module.compact)) ? data.dashboardPlan : fallback;
  const HeaderIcon = iconForPlan[plan.headerIcon] ?? SparklesIcon;
  const Sparkles = HeaderIcon;
  const headerColor = plan.headerAccent === 'dates' ? COLORS.dates : plan.headerAccent === 'cost' ? COLORS.cost : plan.headerAccent === 'place' ? COLORS.place : plan.headerAccent === 'tasks' ? COLORS.tasks : '#7B57A9';
  const openModule = dashboard.expandedSection;
  const costs = data.files.flatMap((file) => file.entities.costs);
  const previewBudget = data.files.find((file) => file.smartPreview.type === 'budget')?.smartPreview.displayData ?? {};
  const initialRows = useMemo<DashboardBudgetRow[]>(() => {
    const rows = Array.isArray(previewBudget.rows) ? previewBudget.rows as Array<{ category?: string; estimate?: number }> : costs.map((cost) => ({ category: cost.label, estimate: cost.amount }));
    return rows.map((row, index) => ({ id: `source-${index}`, category: row.category || 'Other', estimate: typeof row.estimate === 'number' ? row.estimate : 0 }));
  }, [costs, previewBudget]);
  const budgetRows = dashboard.budgetRows ?? initialRows;
  const checklistFile = data.files.find((file) => file.smartPreview.type === 'checklist') ?? data.files.find((file) => file.entities.tasks.length);
  const initialItems = useMemo<DashboardPackingItem[]>(() => {
    const raw = checklistFile && Array.isArray(checklistFile.smartPreview.displayData.items) ? checklistFile.smartPreview.displayData.items as Array<{ text?: string; checked?: boolean }> : checklistFile?.entities.tasks.map((task) => ({ text: task.item, checked: task.completed })) ?? [];
    return raw.map((item, index) => ({ id: `source-${index}`, text: item.text || 'Untitled item', checked: Boolean(item.checked), source: 'file' }));
  }, [checklistFile]);
  const items = dashboard.packingItems ?? initialItems;
  const locations: DashboardLocation[] = data.files.flatMap((file) => file.entities.locations.map((location) => ({ ...location, fileName: file.fileName }))).filter((location, index, all) => all.findIndex((item) => item.name === location.name) === index);
  const total = budgetRows.reduce((sum, row) => sum + row.estimate, 0) || 1;
  const actual = budgetRows.reduce((sum, row) => sum + (row.actual ?? row.estimate), 0);
  const packed = items.filter((item) => item.checked).length;
  const currency = value(previewBudget, 'currency') || costs[0]?.currency || 'USD';
  const patch = (next: Partial<DashboardState>) => emit('aether:dashboard-state', { summaryId: id, patch: next });
  const toggle = (module: DashboardModule) => patch({ expandedSection: openModule === module.id ? undefined : module.id as DashboardState['expandedSection'] });
  const focus = (module: DashboardModule, active: boolean) => emit('aether:summary-section-focus', active ? relationshipFor(module.kind) : null);
  const sourceFiles = (module: DashboardModule) => data.files.filter((file) => module.sourceFileIds.includes(file.id));
  const displayModules = plan.modules.map((module) => module.visual === 'progress' ? { ...module, compact: { ...module.compact, primary: `${packed} / ${items.length}`, secondary: module.title.toLowerCase() === 'packing' ? 'packed' : 'complete' } } : module);
  useEffect(() => { requestAnimationFrame(() => updateNodeInternals(id)); }, [id, openModule, updateNodeInternals]);

  const content = (module: DashboardModule) => {
    const moduleSources = sourceFiles(module);
    if (module.visual === 'route-rail') {
      const dates = data.files.flatMap((file) => file.entities.dates.map((date) => ({ ...date, file }))).sort((left, right) => left.date.localeCompare(right.date)).slice(0, 5);
      return (
        <div className="space-y-3.5">
          <div className="overflow-hidden rounded-[12px] border border-[#DCE8F3] bg-[linear-gradient(145deg,#F9FCFF_0%,#F2F8FD_100%)] shadow-[inset_0_1px_0_rgba(255,255,255,.94)]">
            <div className="flex items-center justify-between border-b border-[#E2ECF5] px-3 py-2"><span className="text-[8px] font-semibold uppercase tracking-[0.13em] text-[#4A7FAF]">Trip flow</span><span className="rounded-full bg-white/70 px-2 py-0.5 text-[8px] font-medium text-[#6683A0]">{dates.length} key moments</span></div>
            <div className="flex items-center justify-between px-3 py-3"><div><b className="block text-[19px] leading-none tracking-[-0.045em] text-[#26313C]">{module.compact.primary}</b><span className="mt-1 block text-[8px] font-medium uppercase tracking-[0.1em] text-[#71879A]">Departure</span></div><div className="mx-3 flex flex-1 items-center gap-1.5 text-[#4A90D9]"><span className="h-px flex-1 border-t border-dashed border-[#ABC8E1]" /><span className="grid h-7 w-7 place-items-center rounded-full bg-white shadow-[0_2px_5px_rgba(45,104,157,.16)]"><Plane size={16} strokeWidth={2.4} /></span><span className="h-px flex-1 border-t border-dashed border-[#ABC8E1]" /></div><div className="text-right"><b className="block text-[19px] leading-none tracking-[-0.045em] text-[#26313C]">{module.compact.secondary}</b><span className="mt-1 block text-[8px] font-medium uppercase tracking-[0.1em] text-[#71879A]">Arrival</span></div></div>
            {module.compact.tertiary && <div className="flex items-center gap-2 border-t border-[#E2ECF5] bg-white/45 px-3 py-2 text-[10px] font-medium text-[#536778]"><span className="grid h-5 w-5 place-items-center rounded-[6px] bg-white text-[#4A90D9] shadow-[0_1px_2px_rgba(45,104,157,.1)]"><CarFront size={12} /></span>{module.compact.tertiary}</div>}
          </div>
          <div><div className="mb-2 flex items-center justify-between"><p className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[#85858C]">Timeline</p><span className="text-[9px] text-[#A09FA5]">From your files</span></div><div className="relative space-y-2 border-l-2 border-[#D8E7F4] pl-4">{dates.map((date, index) => <button className="nodrag relative block w-full rounded-[9px] border border-transparent bg-[#FAFBFC] px-2.5 py-2 text-left transition hover:border-[#DDEAF5] hover:bg-[#F4F9FD] hover:shadow-[0_2px_5px_rgba(42,82,115,.06)]" key={`${date.file.id}-${date.label}`} onClick={() => emit('aether:focus-source-file', date.file.id)} type="button"><span className="absolute -left-[21px] top-3 h-2.5 w-2.5 rounded-full border-2 border-white bg-[#4A90D9] shadow-[0_1px_3px_rgba(34,92,145,.3)]" /><div className="flex items-center gap-2"><span className="rounded-[5px] bg-[#EAF3FB] px-1.5 py-0.5 text-[8px] font-semibold text-[#477EAE]">{date.display}</span><b className="truncate text-[10px] text-[#414149]">{date.label}</b><span className="ml-auto text-[8px] text-[#A09FA5]">{index + 1}</span></div><span className="mt-1 block truncate text-[9px] text-[#8A8990]">Sourced from {date.file.fileName}</span></button>)}</div></div>
          {module.interactions.includes('copy') && <button className="nodrag flex items-center gap-1.5 rounded-[7px] border border-[#D9E6F1] bg-[#F8FBFE] px-2.5 py-1.5 text-[10px] font-medium text-[#4F789D] transition hover:border-[#BFD6EA] hover:bg-[#F0F7FD]" onClick={() => { void navigator.clipboard.writeText(`${module.compact.primary} → ${module.compact.secondary}\n${module.compact.tertiary}`); emit('aether:toast', 'Journey details copied'); }} type="button"><Clipboard size={12} />Copy journey</button>}
        </div>
      );
    }
    if (module.visual === 'ring-metric') return <div className="mt-3"><div className="flex items-center gap-3"><div className="relative grid h-16 w-16 place-items-center"><svg className="h-16 w-16 -rotate-90"><circle cx="32" cy="32" fill="none" r="25" stroke="#E9E9E7" strokeWidth="8" /><motion.circle animate={{ stroke: actual > total ? '#EA4335' : '#34A853', strokeDashoffset: 157 * (1 - Math.min(1, actual / total)) }} cx="32" cy="32" fill="none" r="25" strokeDasharray="157" strokeLinecap="round" strokeWidth="8" /></svg><span className="absolute text-[10px] font-semibold">{money(actual, currency)}</span></div><p className="text-[10px] text-[#66666C]">{actual > total ? `${money(actual - total, currency)} over budget` : `${money(total - actual, currency)} remaining`}</p></div><div className="mt-3 space-y-1">{budgetRows.map((row) => <div className="grid grid-cols-[1fr_58px_58px] gap-1 text-[10px]" key={row.id}><span>{row.category}</span><span className="text-right text-[#77777D]">{money(row.estimate, currency)}</span>{module.interactions.includes('edit-values') ? <input className="nodrag min-w-0 bg-transparent text-right outline-none" onChange={(event) => patch({ budgetRows: budgetRows.map((item) => item.id === row.id ? { ...item, actual: event.target.value ? Number(event.target.value) : undefined } : item) })} placeholder="—" type="number" value={row.actual ?? ''} /> : <span className="text-right">{row.actual === undefined ? '—' : money(row.actual, currency)}</span>}</div>)}</div>{module.interactions.includes('add-item') && <div className="mt-2 flex gap-1"><input className="nodrag min-w-0 flex-1 rounded border px-2 py-1 text-[10px]" onChange={(event) => setExpense((current) => ({ ...current, category: event.target.value }))} placeholder="Expense" value={expense.category} /><input className="nodrag w-16 rounded border px-2 py-1 text-[10px]" onChange={(event) => setExpense((current) => ({ ...current, amount: event.target.value }))} placeholder="Amount" type="number" value={expense.amount} /><button className="nodrag grid h-6 w-6 place-items-center rounded bg-[#34A853] text-white" onClick={() => { if (expense.category && Number(expense.amount)) { patch({ budgetRows: [...budgetRows, { id: crypto.randomUUID(), category: expense.category, estimate: Number(expense.amount) }] }); setExpense({ category: '', amount: '' }); } }} type="button"><Plus size={13} /></button></div>}{module.interactions.includes('export') && <button className="nodrag mt-2 flex items-center gap-1 text-[10px] text-[#77777D]" onClick={() => emit('aether:export-budget', { currency, rows: budgetRows })} type="button"><Download size={12} />Export CSV</button>}</div>;
    if (module.visual === 'progress') return <div className="mt-3"><p className="text-[11px] font-medium">{packed} / {items.length} complete</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#E7E5E9]"><motion.div animate={{ width: `${items.length ? packed / items.length * 100 : 0}%` }} className="h-full bg-[#9B72CF]" /></div><div className="mt-3 space-y-1">{items.map((item) => <button className={`nodrag flex w-full items-center gap-2 text-left text-[10px] ${item.checked ? 'text-[#8A8A90]' : 'text-[#46464B]'}`} disabled={!module.interactions.includes('toggle-item')} key={item.id} onClick={() => patch({ packingItems: items.map((entry) => entry.id === item.id ? { ...entry, checked: !entry.checked } : entry) })} type="button"><span className={`grid h-4 w-4 place-items-center rounded border ${item.checked ? 'border-[#34A853] bg-[#34A853] text-white' : 'border-[#9B9BA0]'}`}>{item.checked && <Check size={11} />}</span><span className={item.checked ? 'line-through' : ''}>{item.text}</span></button>)}</div>{module.interactions.includes('add-item') && <input className="nodrag mt-3 w-full border-b bg-transparent py-1 text-[10px] outline-none" onChange={(event) => setNewItem(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && newItem.trim()) { patch({ packingItems: [...items, { id: crypto.randomUUID(), text: newItem.trim(), checked: false, source: 'user' }] }); setNewItem(''); } }} placeholder="Add item…" value={newItem} />}</div>;
    if (module.visual === 'pin-map') return <div className="mt-3"><InteractiveMap expanded locations={locations} onLocationFocus={(location) => emit('aether:focus-source-file', data.files.find((file) => file.fileName === location.fileName)?.id ?? '')} onOpenDirections={(place) => void window.aether.openExternal(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place)}`)} suggestions={dashboard.aiCache?.map ?? []} /></div>;
    if (module.visual === 'milestone-list') { const dates = data.files.flatMap((file) => file.entities.dates.map((date) => ({ ...date, file }))).sort((left, right) => left.date.localeCompare(right.date)); return <div className="mt-3 space-y-2 border-l-2 border-[#C9DCEF] pl-3">{dates.slice(0, 7).map((date) => <button className="nodrag block text-left text-[10px]" key={`${date.file.id}-${date.label}`} onClick={() => emit('aether:focus-source-file', date.file.id)} type="button"><b className="text-[#3A3A3F]">{date.display}</b><span className="ml-2 text-[#77777D]">{date.label}</span></button>)}</div>; }
    return <div className="mt-3"><p className="text-[10px] leading-4 text-[#626268]">{module.summary}</p><div className="mt-2 space-y-1">{moduleSources.map((file) => <button className="nodrag flex w-full items-center gap-1.5 rounded px-1 py-1 text-left text-[10px] text-[#56565C] hover:bg-[#F5F4F2]" key={file.id} onClick={() => emit('aether:focus-source-file', file.id)} type="button"><FileText size={12} />{file.title}</button>)}</div></div>;
  };

  return (
    <motion.article
      animate={{ opacity: 1, x: 0 }}
      className={`relative w-[332px] overflow-visible rounded-[20px] border bg-[linear-gradient(145deg,#FFFFFF_0%,#FCFCFD_68%,#F9F9FA_100%)] p-4 shadow-[0_18px_42px_rgba(23,23,28,0.13),0_3px_8px_rgba(23,23,28,0.06),inset_0_1px_0_rgba(255,255,255,0.98)] ${selected ? 'border-[#4A90D9] ring-2 ring-[#4A90D9]/15' : 'border-[#D9D8DC]'}`}
      initial={{ opacity: 0, x: 80 }}
      transition={{ delay: data.assemblyDelay ?? 1.2, duration: 0.42, ease: [0.22, 1, 0.36, 1] }}
    >
      <div aria-hidden className="pointer-events-none absolute inset-x-5 top-0 h-px bg-gradient-to-r from-transparent via-white to-transparent" />
      <header className="relative mb-4 flex items-start gap-3 px-0.5 pt-0.5">
        <span className="grid h-11 w-11 shrink-0 place-items-center rounded-[13px] text-white shadow-[inset_0_1px_1px_rgba(255,255,255,.48),0_5px_12px_rgba(40,40,46,.16)]" style={{ background: `linear-gradient(145deg, ${headerColor}, ${headerColor}D4)` }}><Sparkles size={22} strokeWidth={2.15} /></span>
        <div className="min-w-0 flex-1 pt-0.5">
          {editing ? <input autoFocus className="nodrag w-full rounded-[7px] bg-[#F4F3F1] px-1.5 py-0.5 text-[22px] font-semibold tracking-[-0.045em] outline-none ring-2 ring-[#4A90D9]/30" onBlur={() => { if (title.trim()) emit('aether:rename-cluster', { summaryId: id, name: title.trim() }); setEditing(false); }} onChange={(event) => setTitle(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') event.currentTarget.blur(); if (event.key === 'Escape') setEditing(false); }} value={title} /> : <h2 className="truncate text-[22px] font-semibold leading-[1.05] tracking-[-0.05em] text-[#29292E]" onDoubleClick={() => setEditing(true)}>{plan.title || data.cluster.name}</h2>}
          <p className="mt-1.5 text-[11px] font-medium tracking-[-0.01em] text-[#77767D]">{plan.subtitle || data.cluster.dateRange}</p>
        </div>
        <button aria-label="Summary menu" className="nodrag grid h-8 w-8 place-items-center rounded-full text-[#77777E] transition hover:bg-[#F1F0F2] hover:text-[#424249]" onClick={() => setMenu((current) => !current)} type="button"><MoreHorizontal size={19} /></button>
        {menu && <div className="absolute right-0 top-10 z-30 w-44 rounded-[11px] border border-[#DFDEE2] bg-white p-1.5 shadow-[0_12px_28px_rgba(25,25,30,.15)]"><button className="nodrag block w-full rounded-[7px] px-2.5 py-2 text-left text-[10px] font-medium text-[#4B4B52] transition hover:bg-[#F5F4F3]" onClick={() => { setMenu(false); setEditing(true); }} type="button">Rename</button><button className="nodrag flex w-full items-center gap-1.5 rounded-[7px] px-2.5 py-2 text-left text-[10px] font-medium text-[#4B4B52] transition hover:bg-[#F5F4F3]" onClick={() => emit('aether:export-summary', { cluster: { ...data.cluster, name: plan.title || data.cluster.name }, files: data.files, budgetRows, packingItems: items, locations })} type="button"><Download size={12} />Export summary</button><button className="nodrag flex w-full items-center gap-1.5 rounded-[7px] px-2.5 py-2 text-left text-[10px] font-medium text-[#C43E34] transition hover:bg-[#FFF0EE]" onClick={() => emit('aether:remove-cluster', id)} type="button"><X size={12} />Remove cluster</button></div>}
      </header>
      <div className="space-y-2.5">{displayModules.map((module) => <ModuleShell key={module.id} module={module} onHover={(active) => focus(module, active)} onToggle={() => toggle(module)} open={openModule === module.id}>{content(module)}</ModuleShell>)}</div>
      <footer className="mt-4 flex justify-center border-t border-[#EEEDF0] pt-3.5"><button className="nodrag flex items-center gap-1.5 rounded-full border border-[#E4E2E4] bg-[linear-gradient(180deg,#FFFFFF,#F7F7F8)] px-3.5 py-1.5 text-[10px] font-medium text-[#696970] shadow-[inset_0_1px_0_rgba(255,255,255,.95),0_1px_2px_rgba(25,25,30,.04)] transition hover:-translate-y-px hover:border-[#D6D5D9] hover:shadow-[0_4px_9px_rgba(25,25,30,.08)]" onClick={() => emit('aether:highlight-sources', data.files.map((file) => file.id))} type="button"><SparklesIcon className="text-[#8A68AF]" size={13} />Generated from {data.files.length} files</button></footer>
    </motion.article>
  );
}
